[package]
name = "totp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.18", features = ["derive"]}
totp-rs = "2.0.0"




chrono = "0.4"
data-encoding = "2.1.1"
rust-crypto = "^0.2"
byteorder = "1"
openssl = "0.10.10"
hex = "0.3.2"
rpassword = "2.0.0"
