[package]
name = "totp"
version = "0.1.1"
edition = "2021"
authors = ["Krakaw <41575888+Krakaw@users.noreply.github.com>"]

[dependencies]
clap = {version = "3.1.18", features = ["derive"]}
totp-rs = "2.0.0"
chrono = "0.4"
data-encoding = "2.1.1"
openssl = "0.10.10"
rpassword = "2.0.0"
tui = "0.18"
crossterm = "0.23"
cli-clipboard = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
